spring.application.name=librarysystem

spring.datasource.url=jdbc:mysql://library-mysql-db-neu-lib-sys.i.aivencloud.com:16642/defaultdb?sslMode=REQUIRED

spring.datasource.username=avnadmin

spring.datasource.password=AVNS_FDNbNXHAsWPw9462HVX

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true